/* eslint-disable */
/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import { a } from "@aws-amplify/data-schema";
import { configure } from "@aws-amplify/data-schema/internals";
import { secret } from "@aws-amplify/backend";

export const schema = configure({
    database: {
        identifier: "IDba5rJRD7bUMaXwpC9rwdg",
        engine: "postgresql",
        connectionUri: secret("SQL_CONNECTION_STRING")
    }
}).schema({
    "events": a.model({
        event_id: a.integer().required(),
        event_name: a.string().required(),
        event_date: a.date().required(),
        location: a.string(),
        description: a.string()
    }).identifier([
        "event_id"
    ])
});
